services:
  postgres:
    image: postgres:15
    container_name: airline_ops_db
    environment:
      POSTGRES_DB: airline_ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - airline_ops_pgdata:/var/lib/postgresql/data

volumes:
  airline_ops_pgdata: